# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2_login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QDialog, QApplication,QMessageBox
import tkinter as tk
from tkinter import *
from tkinter import messagebox
from PyQt5.uic import loadUi
from config import Config_scr

class Ui_Login_window1(object):
    # function for back button
    def __init__(self):
        self.config_window = None

    def backbutton(self):
        from mainscreen import Ui_MainWindow  # for avoiding circular imports

        self.window2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window2)
        Login_window1.close()
        self.window2.show()

    #  object for login button
    """def __int__(self):
        super(Ui_Login_window1,self).__init__()
        self.loadUi("2_login_page.ui")"""


    def loginfunction(self):
        # username_input
        # password_input
        print("Login button clicked!")
        user = self.username_input.text()
        pwd = self.password_input.text()
        #print("Succesfully logged in with username ", username," and password ",password)
        con = sqlite3.connect(database=r'login.db')
        cursor = con.cursor()

        # Execute the query to check login credentials
        query = "SELECT * FROM login_table WHERE username=? AND password=?"
        cursor.execute(query, (user, pwd))
        result = cursor.fetchone()

        if result:
            print("Login is successful!")
            # Perform actions for successful login here, e.g., show the main application window.
            messagebox.showinfo("showinfo", "Login Successful")
            #calling the class here:
            from config import Config_scr
            self.show_config_window()






        else:
            print("Login failed. Invalid username or password.")
            # Show an error message to the user indicating invalid login credentials.
            messagebox.askretrycancel("askretrycancel", "Incorrect username or password Try again")


        # Close the database connection
        con.close()

        pass

    def show_config_window(self):
        # Function to create and show the Config_scr window
        self.config_window = Config_scr()


        self.config_window.show()





    def setupUi(self, Login_window1):
        Login_window1.setObjectName("Login_window1")
        Login_window1.resize(650, 800)
        Login_window1.setAutoFillBackground(False)
        Login_window1.setStyleSheet("background-color:#003366;")
        self.centralwidget = QtWidgets.QWidget(Login_window1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 320, 121, 41))
        self.label.setStyleSheet("font-color:#fcfcfc;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 400, 121, 51))
        self.label_2.setObjectName("label_2")
        self.login_button1 = QtWidgets.QPushButton(self.centralwidget)
        self.login_button1.setGeometry(QtCore.QRect(374, 510, 81, 41))
        #calling login button here:
        self.login_button1.clicked.connect(self.loginfunction)
        
        self.login_button1.setStyleSheet("background-color:white;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_button1.setIcon(icon)
        self.login_button1.setObjectName("login_button1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 210, 311, 61))
        self.label_4.setObjectName("label_4")
        self.back_button1 = QtWidgets.QPushButton(self.centralwidget)
        self.back_button1.setGeometry(QtCore.QRect(180, 510, 91, 41))
        # calling back button
        self.back_button1.clicked.connect(self.backbutton)
        self.back_button1.setStyleSheet("background-color:white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("back-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button1.setIcon(icon1)
        self.back_button1.setObjectName("back_button1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 110, 91, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("shared-vision.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(180, 220, 61, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("login.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(290, 329, 161, 31))
        self.username_input.setStyleSheet("font-size:12pt;color: rgb(0, 0, 0);background-color:\"white\";\n"
"")
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(290, 410, 161, 31))
        #to hide the password
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setStyleSheet("font-size:12pt;color: rgb(0, 0, 0);background-color:\"white\";")
        self.password_input.setObjectName("password_input")
        Login_window1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login_window1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menubar.setObjectName("menubar")
        Login_window1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login_window1)
        self.statusbar.setObjectName("statusbar")
        Login_window1.setStatusBar(self.statusbar)

        self.retranslateUi(Login_window1)
        QtCore.QMetaObject.connectSlotsByName(Login_window1)

    def retranslateUi(self, Login_window1):
        _translate = QtCore.QCoreApplication.translate
        Login_window1.setWindowTitle(_translate("Login_window1", "MainWindow"))
        self.label.setText(_translate("Login_window1", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Username:</span></p></body></html>"))
        self.label_2.setText(_translate("Login_window1", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">Password:</span></p></body></html>"))
        self.login_button1.setText(_translate("Login_window1", "LOGIN"))
        self.label_4.setText(_translate("Login_window1", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#ff0000;\">LOGIN</span></p></body></html>"))
        self.back_button1.setText(_translate("Login_window1", "BACK"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_window1 = QtWidgets.QMainWindow()
    widget = QtWidgets.QStackedWidget()
    ui = Ui_Login_window1()
    ui.setupUi(Login_window1)
    Login_window1.show()


    sys.exit(app.exec_())
